// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4tY3ctsGiW6MnS1d6u6K5JUvSr_cpBA8',
    appId: '1:153773777928:web:cf183804762f100f10ddbd',
    messagingSenderId: '153773777928',
    projectId: 'kids-ai-train',
    authDomain: 'kids-ai-train.firebaseapp.com',
    storageBucket: 'kids-ai-train.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0klStcKs2GgBeFNiS12qqFmXz_XJLVt0',
    appId: '1:153773777928:android:c86bec49038b775f10ddbd',
    messagingSenderId: '153773777928',
    projectId: 'kids-ai-train',
    storageBucket: 'kids-ai-train.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHF3FqkmwtW1mqZ6_eimoyg4tRLmaIsAE',
    appId: '1:153773777928:ios:07a9bfe2ac0c806d10ddbd',
    messagingSenderId: '153773777928',
    projectId: 'kids-ai-train',
    storageBucket: 'kids-ai-train.firebasestorage.app',
    iosBundleId: 'com.kidsai.parent.kidsAiParent',
  );
}
